### ISSUE TITLE
Improve the "algorithm"

### ISSUE THREAD

**Issue by jacksonconte** [cse210-works-on-my-machine/CSE210-Fall23-Team-3#24]

**Comment by lakshya-4gp** [comment]
Raised a PR to reduce the response time and to show posts in an interleaved fashion for mastodon hashtags

**Comment by lakshya-4gp** [comment]
PR: https://github.com/cse210-works-on-my-machine/CSE210-Fall23-Team-3/pull/32. Merged and closed.
