### ISSUE TITLE
ActivityPub JSON parsing

### ISSUE THREAD

**Issue by jacksonconte** [cse210-works-on-my-machine/CSE210-Fall23-Team-3#5]
Parse ActivityPub JSON responses into a readable "post" format (as a list of posts).

**Comment by shrivaths16** [comment]
Created a prototype that parses the JSON file that is retrieved from the Mastodon API. First, the trending tags are fetched from the `https://mastodon.social/api/v1/trends/tags` API and then using them to fetch posts that contain the tags. 

The prototype can be found in the `om-dev` branch under the folder prototype.

TODO: Work on a logic that gets the ideal set of posts that pertains to the trending content.
