### ISSUE TITLE
Come up with default Mastodon and Lemmy instance lists

### ISSUE THREAD

**Issue by jacksonconte** [cse210-works-on-my-machine/CSE210-Fall23-Team-3#9]

**Comment by realvarunsingh** [comment]
mastodon instances:
[mastodon.social](http://mastodon.social/)
[fosstodon.org](http://fosstodon.org/)
[mstdn.social](http://mstdn.social/)
[mastodon.online](http://mastodon.online/)
[mastodon.world](http://mastodon.world/)

lemmy instances:
[lemmy.ml](http://lemmy.ml/)
[lemmy.world](http://lemmy.world/)
[lemm.ee](http://lemm.ee/)
